### ISSUE TITLE
Add support for JSON?

### ISSUE THREAD

**Issue by adrianpacala** [zilkey/active_api#19]
Don't know about the underlying architecture too much, but could it be possible to add JSON output to active_api?

**Comment by zilkey** [comment]
Sorry for the long delay - I guess I missed the email alert about this one :(

Yes, the plan all along is that once I have the time, I would add a JSON formatter.  My thought is that this could function as the translation layer for any outgoing data for your app, but I don't have a personal need for a json api right now, so I haven't dedicated any time to it.
